apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web
spec:
  type: ClusterIP        # internal only — reachable by Envoy, not exposed to outside
  selector:
    app: web
  ports:
    - name: http
      port: 3000
      targetPort: 3000